### ISSUE TITLE
When I try to create a world the game crashes

### ISSUE THREAD

**Issue by Det-rovv** [nederliver/MinGen#2]
This only happens on mod version 3.5. Minecraft 1.21.1 Neoforge 21.1.92. here is the crush log
[tl-logger11811327332857617488.txt](https://github.com/user-attachments/files/18270350/tl-logger11811327332857617488.txt)

**Comment by nederliver** [comment]
Hi, so basically I added pale garden fallen tree to the 3.5 version but I forgot about versions below 1.21.4, so your instance just crashes, cause Minecraft has no clue how to load it. I will fix that and release fixed version of the data pack soon.
